/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Beatriz Gomez Santamaria (https://sketchfab.com/BeatrizGomez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/e402d3d541eb4b199c57d5410f5d3c57
title: Ecorche - Anatomy study
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/body.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.04, 0.04, 0.04]}>
        <group position={[0.0, 0, -104.06]}>
          <mesh
            material={materials.CleanNickzdefaultMat}
            geometry={nodes.mesh_0.geometry}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/body.glb");
